Screens Manifest Generator Initial Commit
absarasw/aemscreens-offlineresources-generator pull request #1
Opened 2023-03-02 05:20 UTC by absarasw

2023-03-13 13:10 UTC, habansal commented on src/createManifest.js
> +      const resp = await fetch(resourcePath);
can we make a HEAD call here instead of GET (fetch), since we only need the `last-modified` response header?

2023-03-13 13:12 UTC, habansal commented on src/index.js
> +  await GenerateManifests.run(process.argv.slice(2));
As discussed, would be good to have `resourceList` as another parameter to this command so that we generate manifests for only channels with updated resources and not for all channels.

_this can done iteratively as a follow-up PR_

2023-03-13 13:20 UTC, absarasw commented on src/createManifest.js
> +      const resp = await fetch(resourcePath);
done.

2023-03-22 07:12 UTC, vivesing commented
If this is a completely new project that we are creating, I would suggest including TypeScript in this repo. In long run this help in code maintainability

2023-03-22 07:20 UTC, vivesing commented
<img width="1537" alt="image" src="https://user-images.githubusercontent.com/38683124/226828622-735232b4-6ded-4921-a459-b0507ca9a518.png">
In the https://main--franklin-ceasers--absarasw.hlx.page/franklin/screens/menus/manifests.json I see stringified json structure, is this limitation of this manifest.json call?

2023-03-22 08:09 UTC, vivesing requested changes

2023-03-22 08:09 UTC, vivesing commented on src/createManifest.js
> +    const item1 = item.trim();
add undefined check for item

2023-03-22 08:09 UTC, vivesing commented on src/createManifest.js
> +    if (scripts === '') {
add undefined check for scripts, also scripts can be `[]`

2023-03-22 08:09 UTC, vivesing commented on src/createManifest.js
> +    return path.trim().startsWith('/media_');
move string used here "/media" to a constants file

2023-03-22 08:09 UTC, vivesing commented on src/createManifest.js
> +    return path1.substring(7, path1.indexOf('.'));
Use length of "/media_" string instead of hardcoding 7 here

2023-03-22 08:09 UTC, vivesing commented on src/createManifest.js
> +    const pagePath = url + path;
can we use for standard url forming method here, to handle cases like path starting with-without / ending with-without /

2023-03-22 08:09 UTC, vivesing commented on src/createManifest.js
> +    let manifest = '{\n'
trying to understand, why are we using string structure for creating manifest everywhere.

2023-03-22 08:09 UTC, vivesing commented on src/createManifest.js
> +    if (date !== null) {
better check should be if (date)

2023-03-22 08:09 UTC, vivesing commented on src/createManifest.js
> +    for (let i = 0; i < resourcesArr.length; i += 1) {
wouldn't i++ work here?

2023-03-28 06:04 UTC, habansal commented on src/generateManifests.js
> +    outputFile('screens/channels.json', JSON.stringify(channelJson, null, 2), (err) => {
should we either create generateChannelJson or update the name of this file?

2023-03-29 12:08 UTC, absarasw commented on src/createManifest.js
> +    for (let i = 0; i < resourcesArr.length; i += 1) {
eslint throws `no-plusplus` error for that. Will update the config to make ++ operator to work for `for` loops

2023-04-03 09:55 UTC, absarasw commented on src/generateManifests.js
> +    outputFile('screens/channels.json', JSON.stringify(channelJson, null, 2), (err) => {
I have updated the name of the file. It's difficult to take this out since it's dependant on manifest generation.

2023-04-03 10:11 UTC, vivesing commented on src/createManifest.js
> +    const [entries, lastModified] = await CreateManifest.createEntries(host, data.path, resources);
move this above L34, keeps the code cleanby keeping all manifestJson assignment at one place

2023-04-03 10:11 UTC, vivesing commented on src/createManifest.js
> +  static trimImagesPath(item, index, arr) {
please add a single line comment over each method to identify what its doing

2023-04-03 10:11 UTC, vivesing commented on src/createManifest.js
> +    if (date) {
if last-modified is not there we skip entry.timestamp, please add a comment here that timestamp is optional

2023-04-03 10:11 UTC, vivesing commented on src/createManifest.js
> +        continue;
trying to understand the business logic here, when we are unable to fetch the resource we skip it from the manifest, will it not affect the channel rendering in case the asset is not sent in the manifest at the player side?

2023-04-03 10:11 UTC, vivesing commented on src/generateScreensOfflineResources.js
> +    for (let i = 0; i < totalManifests; i += 1) {
use i++ here

2023-04-03 10:12 UTC, vivesing commented
Are we deferring unit tests for now?

2023-04-03 12:38 UTC, absarasw commented on src/createManifest.js
> +        continue;
There are few assets which are not be available but still are part of manifest. They give 404 error in player side, so just to avoid that case. It came as a requirement from player side from Shailendra. We can add retry here.

2023-04-03 12:48 UTC, absarasw commented on src/createManifest.js
> +    const inlineImageList = (inlineImages && inlineImages.length !== 0) ? inlineImages : [];
Only issue was if the json data is not in the format '[]' but an empty string ''. But we can make sure it'll not.

2023-04-05 10:43 UTC, div8063 requested changes

2023-04-05 10:43 UTC, div8063 commented on src/createManifest.js
> +    const [entries, lastModified] = await ManifestGenerator.createEntries(host, path, resources);
The order of usage and definition of functions are different in this class.
Usually, we keep the definitions above and their usages below.

2023-04-05 10:43 UTC, div8063 commented on src/createManifest.js
> +    if ((pageLastModified !== null) && (pageLastModified > lastModified)) {
```suggestion
    if (pageLastModified && pageLastModified > lastModified) {
```

2023-04-05 10:43 UTC, div8063 commented on src/createManifest.js
> +  static async createEntries(host, path, resources) {
```suggestion
  static createEntries = async (host, path, resources) => {
```

2023-04-05 10:43 UTC, div8063 commented on src/createManifest.js
> +  static async createEntries(host, path, resources) {
Can we update all method definitions to use lambda?

2023-04-05 10:43 UTC, div8063 commented on src/createManifest.js
> +    for (let i = 0; i < resourcesArr.length; i++) {
Arrays should be iterated using foreach.
If there are await in loops then you can use:

```
Promise.all(resourcesArr.map((resource) => {
    ...
}
```

But this will run the loops in async. Use only if async execution is fine with your usecase.

2023-04-05 10:43 UTC, div8063 commented on src/createManifest.js
> +      /* eslint-disable no-await-in-loop */
You can avoid this using above suggested approach

2023-04-05 10:43 UTC, div8063 commented on src/generateScreensOfflineResources.js
> +    args.forEach((arg) => {
Lets check if args is an array first before using forEach on it.

2023-04-05 10:43 UTC, div8063 commented on src/generateScreensOfflineResources.js
> +  static async run(args) {
Lets maintain an order for function definitions and their usages.
-> First definition and usages below it (as followed in other screens repos)

2023-04-05 10:43 UTC, div8063 commented on src/generateScreensOfflineResources.js
> +  static createChannelMap(channelsData) {
Lets move the function defintion to lambda one (as followed in other screens repos)

2023-04-05 10:43 UTC, div8063 commented on src/generateScreensOfflineResources.js
> +    const channelsMap = new Map();
Any specific reason to use a map here? 
Asking since a plain JS Object also serves the same purpose.

2023-04-05 10:43 UTC, div8063 commented on src/generateScreensOfflineResources.js
> +    for (let i = 0; i < channelsData.length; i++) {
First check if channelsData is an array and if yes, use foreach with index.

2023-04-05 10:43 UTC, div8063 commented on src/generateScreensOfflineResources.js
> +      const channelData = new Map();
Reason to use map instead of a js object?

2023-04-05 10:43 UTC, div8063 commented on src/generateScreensOfflineResources.js
> +      outputFile(`${manifestData[i].path.substring(1, manifestData[i].path.length)}.manifest.json`, JSON.stringify(manifest, null, 2), (err) => {
```suggestion
      const <varname> =`${manifestData[i].path.substring(1, manifestData[i].path.length)}.manifest.json`; 
      outputFile(<varname>, JSON.stringify(manifest, null, 2), (err) => {
```

2023-04-05 10:43 UTC, div8063 commented on src/utils.js
> +  static async fetchData(host, path) {
I think we will have multiple `fetch` function - this one, one with multiple retries driven by argument.
We should create a separate `fetchUtils` for this.

2023-04-12 12:23 UTC, absarasw commented on src/createManifest.js
> +    for (let i = 0; i < resourcesArr.length; i++) {
Not sure if async execution cause any issue, but I'm keeping it sync for now. Will check if async execution can affect the last modified check.

2023-04-17 07:37 UTC, div8063 requested changes

2023-04-17 07:37 UTC, div8063 commented on src/generateScreensOfflineResources.js
> +    if (parsedArgs.generateLoopingHtml && parsedArgs.generateLoopingHtml === 'true') {
```suggestion
    if (parsedArgs.generateLoopingHtml === 'true') {
```

2023-04-17 07:37 UTC, div8063 commented on src/createManifest.js
> +    if (pageEntryJson.timestamp && (pageEntryJson.timestamp > lastModified)) {
```suggestion
    if (pageEntryJson.timestamp && pageEntryJson.timestamp > lastModified) {
```

2023-04-17 07:37 UTC, div8063 commented on src/createManifest.js
> +      const date = resp.headers.get('last-modified');
Lets move it to line 87 for better context

2023-04-17 08:09 UTC, absarasw commented on src/utils.js
> +  static async fetchData(host, path) {
Will be done through next PR

2023-04-17 08:09 UTC, absarasw commented on src/generateScreensOfflineResources.js
> +    const channelsMap = new Map();
We needed a key value pair to check on the basis of channel path

2023-04-17 08:12 UTC, merged